server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: CartService
          uri: http://localhost:8081/
          predicates:
            - Path=/cart/**
        - id: ProductService
          uri: http://localhost:8082/
          predicates:
            - Path=/products/**